In [1]:
%pip install lxml

Requirement already satisfied: lxml in /usr/local/python/3.12.1/lib/python3.12/site-packages (6.0.2)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
%pip install pandas

Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
%pip install wikipedia

Requirement already satisfied: wikipedia in /usr/local/python/3.12.1/lib/python3.12/site-packages (1.4.0)
Requirement already satisfied: beautifulsoup4 in /home/codespace/.local/lib/python3.12/site-packages (from wikipedia) (4.14.2)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /home/codespace/.local/lib/python3.12/site-packages (from wikipedia) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/codespace/.local/lib/python3.12/site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/codespace/.local/lib/python3.12/site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/codespace/.local/lib/python3.12/site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/codespace/.local/lib/python3.12/site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2025.11.12)
Requirement already satisfied: soupsieve>1.2 in /home/codespace/.local/lib/python3.12/site-packages (from beautifulsoup4->wikipedia) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /home/codespace/.local/lib/python3.12/site-packages (from beautifulsoup4->wikipedia) (4.15.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

## create dummy data

In [1]:
import pandas as pd
import wikipedia
import io

In [2]:
wiki_page=wikipedia.page(r'ISO_3166-1',auto_suggest = False).html()

In [3]:
tables=pd.read_html(io.StringIO(wiki_page))

In [5]:
tables[1].iloc[0:1]

,Short name upper case in ISO 3166,Short name lower case in ISO 3166 Full name,Listed as independent in ISO 3166,Local short name,Dispute,Link to ISO 3166-2
0,AFGHANISTAN,Afghanistanthe Islamic Republic of Afghanistan,Yes[6],Afghānistān (ps) Afghānistān (fa),Under the unrecognized government of the Islam...,ISO 3166-2:AF

In [6]:
tables[1].to_csv('dir_diff/dir1/disputed.csv',index=False) 
tables[1].to_csv('dir_diff/dir2/disputed.csv',index=False)

In [7]:
tables[2].iloc[0:1]

,English short name (using title case),Alpha-2 code,Alpha-3 code,Numeric code,Link to ISO 3166-2,Independent[b]
0,Afghanistan[c],AF,AFG,4,ISO 3166-2:AF,Yes

In [5]:
tables[1].to_csv('dir_diff/dir1/name_code.csv',index=False) 
tables[1].to_csv('dir_diff/dir2/name_code.csv',index=False) 
tables[1].to_csv('dir_diff/dir2/~name_code.csv',index=False) #additional copy

In [9]:
tables[2].iloc[0:1]

,English short name (using title case),Alpha-2 code,Alpha-3 code,Numeric code,Link to ISO 3166-2,Independent[b]
0,Afghanistan[c],AF,AFG,4,ISO 3166-2:AF,Yes

In [10]:
tables[2].to_csv('dir_diff/dir1/version_control.csv',index=False) 
tables[2].iloc[2:].to_csv('dir_diff/dir2/version_control.csv',index=False) #corrupted copy

## Directory comparison

In [12]:
ls -l dir_diff

total 8
drwxrwxrwx+ 2 codespace root 4096 Apr  5 13:40 dir1/
drwxrwxrwx+ 2 codespace root 4096 Apr  5 13:40 dir2/

In [13]:
ls -l dir_diff/*

dir_diff/dir1:
total 28
-rw-rw-rw- 1 codespace root  1132 Apr  5 18:54 disputed.csv
-rw-rw-rw- 1 codespace root 10391 Apr  5 13:40 name_code.csv
-rw-rw-rw- 1 codespace root 10394 Apr  5 18:55 version_control.csv

dir_diff/dir2:
total 40
-rw-rw-rw- 1 codespace root  1132 Apr  5 18:54  disputed.csv
-rw-rw-rw- 1 codespace root 10391 Apr  5 13:40  name_code.csv
-rw-rw-rw- 1 codespace root 10309 Apr  5 18:55  version_control.csv
-rw-rw-rw- 1 codespace root 10391 Apr  5 13:40 '~name_code.csv'

In [14]:
ls -l dir_diff/*/*

-rw-rw-rw- 1 codespace root  1132 Apr  5 18:54 dir_diff/dir1/disputed.csv
-rw-rw-rw- 1 codespace root 10391 Apr  5 13:40 dir_diff/dir1/name_code.csv
-rw-rw-rw- 1 codespace root 10394 Apr  5 18:55 dir_diff/dir1/version_control.csv
-rw-rw-rw- 1 codespace root  1132 Apr  5 18:54 dir_diff/dir2/disputed.csv
-rw-rw-rw- 1 codespace root 10391 Apr  5 13:40 dir_diff/dir2/name_code.csv
-rw-rw-rw- 1 codespace root 10309 Apr  5 18:55 dir_diff/dir2/version_control.csv
-rw-rw-rw- 1 codespace root 10391 Apr  5 13:40 dir_diff/dir2/~name_code.csv

the glob is preferrable as it skips the directory name and the totals, but includes the path in the filename

In [16]:
!ls -l dir_diff/*/* > diff.txt

In [18]:
list_of_headers=['permissions', 'hard_links','user','group','size','month','day','time','path']
dir_listing=pd.read_csv('diff.txt', sep=r'\s+',names=list_of_headers)

In [19]:
def split_path(df):
    return (df
            .assign(parent_dir=df
                    .path
                    .str.split(pat='/',expand=True)[0],
                    inner_dir=df
                    .path
                    .str.split(pat='/',expand=True)[1],
                    filename=df
                    .path
                    .str.split(pat='/',expand=True)[2]
                    )
            )

In [20]:
dir_listing.pipe(split_path).groupby(['inner_dir']).agg({'filename':'count','size':'sum'})

           filename   size
inner_dir
dir1              3  21917
dir2              4  32223

In [21]:
(dir_listing
 .pipe(split_path)
 .groupby(['filename','inner_dir'])
 .agg({'filename':'count','size':'sum'}) # Identify additional file in dir2, inconsistent size
 .unstack()
)

                    filename          size
inner_dir               dir1 dir2     dir1     dir2
filename
disputed.csv             1.0  1.0   1132.0   1132.0
name_code.csv            1.0  1.0  10391.0  10391.0
version_control.csv      1.0  1.0  10394.0  10309.0
~name_code.csv           NaN  1.0      NaN  10391.0